import React, { useState } from 'react';
import type { WeeklyReportData } from '../types/habit';
import { X, Copy, Check, Trophy, Calendar, Sparkles } from 'lucide-react';

interface WeeklyReportModalProps {
  report: WeeklyReportData;
  onClose: () => void;
}

export const WeeklyReportModal: React.FC<WeeklyReportModalProps> = ({ report, onClose }) => {
  const [copied, setCopied] = useState(false);

  const formattedTextReport = `
========================================
🏆 HABBIT TRACKER - WEEKLY OUTPUT REPORT
========================================
🗓️ Week: ${report.weekLabel}
📊 Overall Score: ${report.overallCompletionPercentage}%
✅ Habits Logged: ${report.totalHabitsLogged} / ${report.totalPossibleHabits}
🌟 Best Day: ${report.bestDay}

HABIT CONSISTENCY BREAKDOWN:
----------------------------------------
${report.habitSummaries
  .map(
    (s) =>
      `${s.percentage >= 80 ? '🟢' : s.percentage >= 50 ? '🟡' : '🔴'} ${s.habit.name}: ${s.completedCount}/7 days (${s.percentage}%)`
  )
  .join('\n')}

🔥 Top Performing Habits:
${report.topHabits.map((h, i) => `   ${i + 1}. ${h}`).join('\n')}
========================================
Generated by Habbit Tracker App
`.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(formattedTextReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="glass-card max-w-lg w-full max-h-[90vh] overflow-y-auto p-5 space-y-4 bg-slate-900 border-indigo-500/30">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Trophy className="w-5 h-5 text-amber-400" />
            <h3 className="font-extrabold text-lg text-white">Weekly Output Report</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-slate-800 text-slate-400 hover:text-white transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-3 font-mono text-xs text-slate-300">
          <div className="flex items-center justify-between text-indigo-400 font-bold border-b border-slate-800 pb-2">
            <span className="flex items-center gap-1.5">
              <Calendar className="w-4 h-4" />
              {report.weekLabel}
            </span>
            <span className="text-emerald-400 text-sm">{report.overallCompletionPercentage}%</span>
          </div>

          <div className="space-y-1 text-slate-200">
            <div>
              Total Habits Completed: <strong className="text-emerald-400">{report.totalHabitsLogged}</strong> / {report.totalPossibleHabits}
            </div>
            <div>
              Best Performing Day: <strong className="text-amber-300">{report.bestDay}</strong>
            </div>
          </div>

          <div className="pt-2 border-t border-slate-800 space-y-1">
            <div className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">
              Individual Habit Scores
            </div>
            {report.habitSummaries.map((s) => (
              <div key={s.habit.id} className="flex justify-between items-center py-0.5">
                <span className="truncate max-w-[200px]">{s.habit.name}</span>
                <span className="font-bold">
                  {s.completedCount}/7 ({s.percentage}%)
                </span>
              </div>
            ))}
          </div>

          {report.topHabits.length > 0 && (
            <div className="pt-2 border-t border-slate-800 text-amber-300 space-y-1">
              <div className="flex items-center gap-1 font-bold text-[10px] uppercase text-amber-400">
                <Sparkles className="w-3 h-3" /> Top Stars
              </div>
              {report.topHabits.map((h, i) => (
                <div key={i}>★ {h}</div>
              ))}
            </div>
          )}
        </div>

        <div className="flex gap-3 pt-2">
          <button
            onClick={handleCopy}
            className="flex-1 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-sm flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/30 transition"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                Copied to Clipboard!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy Text Report
              </>
            )}
          </button>

          <button
            onClick={onClose}
            className="px-5 py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 font-semibold text-sm transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
